### ISSUE TITLE
АНО НЕ КАМПАЙЛИЦА

### ISSUE THREAD

**Issue by LLIkolnik** [Tech3434/Techno-Phoenix#1]
Я КАРОЧИ ТАКОЙ ГАВРЮ ЕМУ 
- СУКА КАМПАЙЛИС
А ОН ТАКОЙ
- НИТ)))00))000)00))00))))))))00

**Comment by Tech3434** [comment]
На моей машине, а так же на второй и третьей компайлится. Так что закрываю ишьюз, проблема не на нашей стороне.

**Comment by Tech3434** [comment]
Ну, или на нашей, но я фиксанул.
