### ISSUE TITLE
ЕРП механ

### ISSUE THREAD

**Issue by alexix1989** [Tech3434/Techno-Phoenix#15]
Нельзя взаимодействовать с собой.

**Comment by LLIkolnik** [comment]
![image](https://user-images.githubusercontent.com/32063181/46211727-890f5800-c334-11e8-83a7-46d06b44476c.png)

Не баг от слова совсем, всё было изначально задумано так.

**Comment by Tech3434** [comment]
1. Есть эмоут 'fap', который заменяет интеракты с собой.
2. А что ты-бы хотел видеть при взаимодействии с собой?
