### ISSUE TITLE
?

### ISSUE THREAD

**Issue by SFMUC** [Tech3434/Techno-Phoenix#2]
ERT база.
Смысл этой комнаты, если тут..ничего нет? Хотя бы....там...Voidsuit'ы?
![image](https://user-images.githubusercontent.com/41264037/45689690-4ba11280-bb5d-11e8-99b9-e15f8b7002f0.png)

Bio-suit'ы, лежащие в шкафчике/на полу невидимы..
![image](https://user-images.githubusercontent.com/41264037/45689762-712e1c00-bb5d-11e8-88ee-728fa3f2c536.png)

Комната Gym'a названа.....все еще Locker Room?
![image](https://user-images.githubusercontent.com/41264037/45689986-fb768000-bb5d-11e8-93fe-3418b382dcc9.png)
![image](https://user-images.githubusercontent.com/41264037/45690007-0a5d3280-bb5e-11e8-9d77-f0b23645a4df.png)

111,185,3...Тут....должно быть что-то?
![image](https://user-images.githubusercontent.com/41264037/45690470-07af0d00-bb5f-11e8-8292-92777be5c1a4.png)

В шкафчиках местной охраны лежит Маузер, и магазин...от...Люгера?

125.163.3 Медицинское крыло местной охраны. Освещения вообще нету.(Спасибо ПНВ за хорошую работу)
![image](https://user-images.githubusercontent.com/41264037/45691067-7a6cb800-bb60-11e8-9598-ac1df12874b8.png)
(Ах да, в этой комнате еще AirAlarm и шлюз в тех. туннели названы странно.)
![image](https://user-images.githubusercontent.com/41264037/45691148-a8ea9300-bb60-11e8-9bec-92e725517501.png)
![image](https://user-images.githubusercontent.com/41264037/45691154-ac7e1a00-bb60-11e8-8e62-d880e90631ca.png)
![image](https://user-images.githubusercontent.com/41264037/45691175-bdc72680-bb60-11e8-94ec-9c751b74e225.png)

152.149.2 Лестница ведет в....никуда.
![image](https://user-images.githubusercontent.com/41264037/45691326-0f6fb100-bb61-11e8-9aae-feb7c538fc37.png)
![image](https://user-images.githubusercontent.com/41264037/45691330-13033800-bb61-11e8-9f41-d0070aefa316.png)

Большинство таких лестниц....не работают. 
![image](https://user-images.githubusercontent.com/41264037/45691823-0206f680-bb62-11e8-8004-9a69bfd3bf27.png)

146.142.3 Космо-пивко...невидимо в этом шкафчике.
![image](https://user-images.githubusercontent.com/41264037/45692436-69717600-bb63-11e8-9c59-b5fb883b825e.png)

Решил релеватор вколоть главе ревы, просканить его, и...(Возможно я сделал что-то не так...)
![image](https://user-images.githubusercontent.com/41264037/45692902-8e1a1d80-bb64-11e8-84f9-4c9590945358.png)

(Brainding device) Тяжело было перевести последних 3?
![image](https://user-images.githubusercontent.com/41264037/45692989-bdc92580-bb64-11e8-922a-32fc13e19b7f.png)

149.103.3 Раковина в NanoMed'e. Новые технологии, yey.
![image](https://user-images.githubusercontent.com/41264037/45693765-76dc2f80-bb66-11e8-8775-d1d78d57ea86.png)

Скреллы. Им больно.
![image](https://user-images.githubusercontent.com/41264037/45693941-e4885b80-bb66-11e8-9d0c-364ba914f923.png)

~20-30 еще осталось.
Удачи.
 -DoomGuy&Dagger17

**Comment by n0rm4ld3f4ult** [comment]
АХАХ блять.
кхем
Ксеносов быть не должно.
шутка внизу
_Thief - капиталист
rapist - фашист
criminal - криминал_
^шутка!!
The Loyality scanner machine создана для проверки Идеологии(фашизм=лоялист. не фашизм=не очень лоялист).
А там их и нету, блять!
![default](https://user-images.githubusercontent.com/33929706/45694963-1995ad80-bb69-11e8-8958-25e226ecb61d.png)
С остальным согласен, чинить надо.

**Comment by SFMUC** [comment]
>Ксеносов быть не должно.

Да, не должно...Но они есть :jerry:

> А там их и нету, блять!
> ![default](https://user-images.githubusercontent.com/33929706/45694963-1995ad80-bb69-11e8-8958-25e226ecb61d.png)

Тогда смысл от ебаных шкафчиков там?
Энивей, biosuit и остальное невидимы.
![image](https://user-images.githubusercontent.com/41264037/45695304-cec86580-bb69-11e8-816d-2d1d9bc60b7b.png)


>The Loyality scanner machine создана для проверки Идеологии(фашизм=лоялист. не фашизм=не очень лоялист).

Я чекал на разных идеологиях - всегда писало "Лоялен", meh



>шутка внизу
>Thief - капиталист
>rapist - фашист
>criminal - криминал
>^шутка!!

Ой, ебать вы смешной. Но у Бога с тобой вышло смешнее.(На самом деле, 4nr их не перевели тоже.)

**Comment by n0rm4ld3f4ult** [comment]
Ступил, не фашисты, а монархисты. Ну хрен знает.
![default](https://user-images.githubusercontent.com/33929706/45696450-51522480-bb6c-11e8-95aa-e642b66a3640.png)
Отодвинуть не пробовал? Слои не очень.
![default](https://user-images.githubusercontent.com/33929706/45696639-af7f0780-bb6c-11e8-83c8-95ba18b739a6.png)

**Comment by SFMUC** [comment]
>Отодвинуть не пробовал? Слои не очень.

Вроде пытался, но не особо помогало.

**Comment by Tech3434** [comment]
13ff8361cf56de05447f1017903f3facd3675893
d784ce8529883c2e8d51071476237d1336226e2f
e64f50a3dcb170c0c2f358807fd78e9e8536cb08
Всё починено, кроме скреллов и невидимых вещей в шкафах. Второе вроде не чинится, посмотрю потом.
И да, сканер показывает, является-ли объект фашистом/коммунистом/либертарианстом (Или как это пишется?). И то, лишь если у объекта в крови нет ан-ревелатора.
И да, чтобы просканировать, нужно ввести ревелатор. Если сканер емагнут, то он выдаст рандомом, либо "Он лоялен", либо "Он вероятно не лоялен".
И, да, ответа "Он не лоялен" нет.
И на роли это никак не отображается, чекается лишь идеология.
