### ISSUE TITLE
Нерабочая лестница

### ISSUE THREAD

**Issue by Phelps22** [Tech3434/Techno-Phoenix#22]
Лестница в техтоннеле гидропоники никуда не ведёт. Так и выдаёт, что она not finished.

**Comment by n0rm4ld3f4ult** [comment]
К слову, она действительно никуда не ведёт.
По её координатам она ведёт на подиум клоуна.
Уберу её за ненадобностью.
~~я бы с радостью закрыл иссуй но я не могу~~

**Comment by Tech3434** [comment]
23df2721c89a4351ebd8e76ef04e36023b396a85
