### ISSUE TITLE
cYka

### ISSUE THREAD

**Issue by n0rm4ld3f4ult** [Tech3434/Techno-Phoenix#3]
Решил отписать сюда тоже... Мне ведь тоже это чинить.
1. Только боевые патроны в арсенале.
2. Неправильные магазины в шкафчиках СБ(маузер к люгеру..?)
3. Один и тот же доступ у главы Тайной Полиции(аббревиатура гениальная, ТП, бля!)
4. Половина шлюзов непрозрачные, но просматриваются.

**Comment by SFMUC** [comment]
Ты бы лучше присмотрелся к шлюзам, и алт. формам глав. Там смешное

**Comment by Tech3434** [comment]
3. 801523cd66403c692cfb59fdeabfcddd5fdb1ad1
Если ещё где, то скажи.

**Comment by AmbrosiaBlyatFumari** [comment]
короче я по жизни вор и не стыжусь, вот вам место откуда можно воровать одежку для фашни вроде касочек медиков и не только одежду ДЛЯ ФАШНИ!!!00 Можно попиздить одежду коммуняг и впилить их как нюку но мне похуй. 
https://github.com/WW2-SS13/WW13/tree/master/icons

**Comment by n0rm4ld3f4ult** [comment]
> 
> 
> короче я по жизни вор и не стыжусь, вот вам место откуда можно воровать одежку для фашни вроде касочек медиков и не только одежду ДЛЯ ФАШНИ!!!00 Можно попиздить одежду коммуняг и впилить их как нюку но мне похуй.
> https://github.com/WW2-SS13/WW13/tree/master/icons

Ты не удивишься, но бОльшая часть спрайтов там - отсюда

**Comment by AmbrosiaBlyatFumari** [comment]
Я так и понял но я это поищу еще место откуда можно воровать БОЛЬШЕ я же так понял вы не собираетесь нанимать профи-спрайтера-228 который вам все сделает

**Comment by n0rm4ld3f4ult** [comment]
> 
> 
> Я так и понял но я это поищу еще место откуда можно воровать БОЛЬШЕ я же так понял вы не собираетесь нанимать профи-спрайтера-228 который вам все сделает

у нас вроде есть один.

**Comment by AmbrosiaBlyatFumari** [comment]
а давайте добавим милых девочек и мальчиков  
![george_harvey-1503488687](https://user-images.githubusercontent.com/43430615/45833128-8d23f000-bd0c-11e8-93e7-03cdbbf71c51.jpg)

**Comment by SFMUC** [comment]
> а давайте добавим милых девочек и мальчиков
> ![george_harvey-1503488687](https://user-images.githubusercontent.com/43430615/45833128-8d23f000-bd0c-11e8-93e7-03cdbbf71c51.jpg)

"Дети меня не заводили, пока я не завел себе детей"

**Comment by AmbrosiaBlyatFumari** [comment]
![1521529934143927532](https://user-images.githubusercontent.com/43430615/45833271-fd327600-bd0c-11e8-8556-47af1f2a792c.jpg)

**Comment by AmbrosiaBlyatFumari** [comment]
ВЕРНИТИ ЛОУДАУТ!!!!! И чтоб ушанка на месте была

**Comment by VoiceInYourHead** [comment]
У Директора Тайной Полиции нет доступа к мостику, и собственному кабинету.
