### ISSUE TITLE
 ?

### ISSUE THREAD

**Issue by SFMUC** [Tech3434/Techno-Phoenix#5]

**Comment by n0rm4ld3f4ult** [comment]
Насчёт туалета кэпского - так везде, совсем везде.
Ты мне даже однажды советовал взломать стену в кэпскую через душ, сказав, что она дверь не имеет доступа

**Comment by SFMUC** [comment]
>Ты мне даже однажды советовал взломать стену в кэпскую через душ, сказав, что она дверь не имеет доступа 

Торчик, помню.

**Comment by SFMUC** [comment]
Ах да, новые *правила* моих ишьюзов. Have fun =/

**Comment by Tech3434** [comment]
Пустой ишьюз, закрываю.
